repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt
        language: system
        args: [-w]
        files: \.go$
      
      - id: go-vet
        name: go vet
        entry: go
        language: system
        args: [vet, ./...]
        files: \.go$
        pass_filenames: false
      
      - id: go-test
        name: go test
        entry: go
        language: system
        args: [test, -race, ./...]
        files: \.go$
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files