# Example YAML configuration for struct-based konfig usage
# This file demonstrates how to structure YAML for use with LoadInto()

service:
  name: "konfig-example-app"
  version: "1.0.0"
  environment: "development"

application:
  debug: true
  description: "Example application demonstrating konfig struct-based configuration"

server:
  host: "0.0.0.0"
  port: ${SERVER_PORT:8080}
  timeout: "30s"

database:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:myapp}
  username: ${DB_USER:postgres}
  password: ${DB_PASSWORD:secret}
  ssl_mode: ${DB_SSL_MODE:disable}
  pool_size: ${DB_POOL_SIZE:10}

cache:
  enabled: ${CACHE_ENABLED:false}
  url: ${CACHE_URL:redis://localhost:6379}
  ttl: ${CACHE_TTL:300}

logging:
  level: ${LOG_LEVEL:info}
  format: ${LOG_FORMAT:json}

metrics:
  enabled: ${METRICS_ENABLED:true}
  port: ${METRICS_PORT:9090}
  path: "/metrics"