name: Next Version

on:
  push:
    branches:
      - main

jobs:
  NextVersion:
    runs-on: ubuntu-latest

    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true